/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProjectVideoImmersionLazyImport = createFileRoute(
  '/project/video-immersion',
)()
const ProjectHorizontalVirtualSlideLazyImport = createFileRoute(
  '/project/horizontal-virtual-slide',
)()
const ProjectFastCarouselLazyImport = createFileRoute(
  '/project/fast-carousel',
)()
const ProjectDynamicModalLazyImport = createFileRoute(
  '/project/dynamic-modal',
)()
const ProjectCubicBezierArrowsLazyImport = createFileRoute(
  '/project/cubic-bezier-arrows',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectVideoImmersionLazyRoute = ProjectVideoImmersionLazyImport.update({
  path: '/project/video-immersion',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/project/video-immersion.lazy').then((d) => d.Route),
)

const ProjectHorizontalVirtualSlideLazyRoute =
  ProjectHorizontalVirtualSlideLazyImport.update({
    path: '/project/horizontal-virtual-slide',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/project/horizontal-virtual-slide.lazy').then(
      (d) => d.Route,
    ),
  )

const ProjectFastCarouselLazyRoute = ProjectFastCarouselLazyImport.update({
  path: '/project/fast-carousel',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/project/fast-carousel.lazy').then((d) => d.Route),
)

const ProjectDynamicModalLazyRoute = ProjectDynamicModalLazyImport.update({
  path: '/project/dynamic-modal',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/project/dynamic-modal.lazy').then((d) => d.Route),
)

const ProjectCubicBezierArrowsLazyRoute =
  ProjectCubicBezierArrowsLazyImport.update({
    path: '/project/cubic-bezier-arrows',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/project/cubic-bezier-arrows.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/cubic-bezier-arrows': {
      id: '/project/cubic-bezier-arrows'
      path: '/project/cubic-bezier-arrows'
      fullPath: '/project/cubic-bezier-arrows'
      preLoaderRoute: typeof ProjectCubicBezierArrowsLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/dynamic-modal': {
      id: '/project/dynamic-modal'
      path: '/project/dynamic-modal'
      fullPath: '/project/dynamic-modal'
      preLoaderRoute: typeof ProjectDynamicModalLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/fast-carousel': {
      id: '/project/fast-carousel'
      path: '/project/fast-carousel'
      fullPath: '/project/fast-carousel'
      preLoaderRoute: typeof ProjectFastCarouselLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/horizontal-virtual-slide': {
      id: '/project/horizontal-virtual-slide'
      path: '/project/horizontal-virtual-slide'
      fullPath: '/project/horizontal-virtual-slide'
      preLoaderRoute: typeof ProjectHorizontalVirtualSlideLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/video-immersion': {
      id: '/project/video-immersion'
      path: '/project/video-immersion'
      fullPath: '/project/video-immersion'
      preLoaderRoute: typeof ProjectVideoImmersionLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  ProjectCubicBezierArrowsLazyRoute,
  ProjectDynamicModalLazyRoute,
  ProjectFastCarouselLazyRoute,
  ProjectHorizontalVirtualSlideLazyRoute,
  ProjectVideoImmersionLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/project/cubic-bezier-arrows",
        "/project/dynamic-modal",
        "/project/fast-carousel",
        "/project/horizontal-virtual-slide",
        "/project/video-immersion"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/project/cubic-bezier-arrows": {
      "filePath": "project/cubic-bezier-arrows.lazy.tsx"
    },
    "/project/dynamic-modal": {
      "filePath": "project/dynamic-modal.lazy.tsx"
    },
    "/project/fast-carousel": {
      "filePath": "project/fast-carousel.lazy.tsx"
    },
    "/project/horizontal-virtual-slide": {
      "filePath": "project/horizontal-virtual-slide.lazy.tsx"
    },
    "/project/video-immersion": {
      "filePath": "project/video-immersion.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
