/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FeaturesLazyImport = createFileRoute('/features')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const FeaturesVideoImmersionLazyImport = createFileRoute(
  '/features/video-immersion',
)()
const FeaturesTrelloApiLazyImport = createFileRoute('/features/trello-api')()
const FeaturesHorizontalVirtualSlideLazyImport = createFileRoute(
  '/features/horizontal-virtual-slide',
)()
const FeaturesFastCarouselLazyImport = createFileRoute(
  '/features/fast-carousel',
)()
const FeaturesDynamicModalLazyImport = createFileRoute(
  '/features/dynamic-modal',
)()
const FeaturesCubicBezierArrowsLazyImport = createFileRoute(
  '/features/cubic-bezier-arrows',
)()

// Create/Update Routes

const FeaturesLazyRoute = FeaturesLazyImport.update({
  path: '/features',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/features.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FeaturesVideoImmersionLazyRoute = FeaturesVideoImmersionLazyImport.update(
  {
    path: '/video-immersion',
    getParentRoute: () => FeaturesLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/features/video-immersion.lazy').then((d) => d.Route),
)

const FeaturesTrelloApiLazyRoute = FeaturesTrelloApiLazyImport.update({
  path: '/trello-api',
  getParentRoute: () => FeaturesLazyRoute,
} as any).lazy(() =>
  import('./routes/features/trello-api.lazy').then((d) => d.Route),
)

const FeaturesHorizontalVirtualSlideLazyRoute =
  FeaturesHorizontalVirtualSlideLazyImport.update({
    path: '/horizontal-virtual-slide',
    getParentRoute: () => FeaturesLazyRoute,
  } as any).lazy(() =>
    import('./routes/features/horizontal-virtual-slide.lazy').then(
      (d) => d.Route,
    ),
  )

const FeaturesFastCarouselLazyRoute = FeaturesFastCarouselLazyImport.update({
  path: '/fast-carousel',
  getParentRoute: () => FeaturesLazyRoute,
} as any).lazy(() =>
  import('./routes/features/fast-carousel.lazy').then((d) => d.Route),
)

const FeaturesDynamicModalLazyRoute = FeaturesDynamicModalLazyImport.update({
  path: '/dynamic-modal',
  getParentRoute: () => FeaturesLazyRoute,
} as any).lazy(() =>
  import('./routes/features/dynamic-modal.lazy').then((d) => d.Route),
)

const FeaturesCubicBezierArrowsLazyRoute =
  FeaturesCubicBezierArrowsLazyImport.update({
    path: '/cubic-bezier-arrows',
    getParentRoute: () => FeaturesLazyRoute,
  } as any).lazy(() =>
    import('./routes/features/cubic-bezier-arrows.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesLazyImport
      parentRoute: typeof rootRoute
    }
    '/features/cubic-bezier-arrows': {
      id: '/features/cubic-bezier-arrows'
      path: '/cubic-bezier-arrows'
      fullPath: '/features/cubic-bezier-arrows'
      preLoaderRoute: typeof FeaturesCubicBezierArrowsLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
    '/features/dynamic-modal': {
      id: '/features/dynamic-modal'
      path: '/dynamic-modal'
      fullPath: '/features/dynamic-modal'
      preLoaderRoute: typeof FeaturesDynamicModalLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
    '/features/fast-carousel': {
      id: '/features/fast-carousel'
      path: '/fast-carousel'
      fullPath: '/features/fast-carousel'
      preLoaderRoute: typeof FeaturesFastCarouselLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
    '/features/horizontal-virtual-slide': {
      id: '/features/horizontal-virtual-slide'
      path: '/horizontal-virtual-slide'
      fullPath: '/features/horizontal-virtual-slide'
      preLoaderRoute: typeof FeaturesHorizontalVirtualSlideLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
    '/features/trello-api': {
      id: '/features/trello-api'
      path: '/trello-api'
      fullPath: '/features/trello-api'
      preLoaderRoute: typeof FeaturesTrelloApiLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
    '/features/video-immersion': {
      id: '/features/video-immersion'
      path: '/video-immersion'
      fullPath: '/features/video-immersion'
      preLoaderRoute: typeof FeaturesVideoImmersionLazyImport
      parentRoute: typeof FeaturesLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  FeaturesLazyRoute: FeaturesLazyRoute.addChildren({
    FeaturesCubicBezierArrowsLazyRoute,
    FeaturesDynamicModalLazyRoute,
    FeaturesFastCarouselLazyRoute,
    FeaturesHorizontalVirtualSlideLazyRoute,
    FeaturesTrelloApiLazyRoute,
    FeaturesVideoImmersionLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/features"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/features": {
      "filePath": "features.lazy.tsx",
      "children": [
        "/features/cubic-bezier-arrows",
        "/features/dynamic-modal",
        "/features/fast-carousel",
        "/features/horizontal-virtual-slide",
        "/features/trello-api",
        "/features/video-immersion"
      ]
    },
    "/features/cubic-bezier-arrows": {
      "filePath": "features/cubic-bezier-arrows.lazy.tsx",
      "parent": "/features"
    },
    "/features/dynamic-modal": {
      "filePath": "features/dynamic-modal.lazy.tsx",
      "parent": "/features"
    },
    "/features/fast-carousel": {
      "filePath": "features/fast-carousel.lazy.tsx",
      "parent": "/features"
    },
    "/features/horizontal-virtual-slide": {
      "filePath": "features/horizontal-virtual-slide.lazy.tsx",
      "parent": "/features"
    },
    "/features/trello-api": {
      "filePath": "features/trello-api.lazy.tsx",
      "parent": "/features"
    },
    "/features/video-immersion": {
      "filePath": "features/video-immersion.lazy.tsx",
      "parent": "/features"
    }
  }
}
ROUTE_MANIFEST_END */
