/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as FeaturesVideoImmersionRouteImport } from './routes/features/video-immersion'
import { Route as FeaturesTrelloApiRouteImport } from './routes/features/trello-api'
import { Route as FeaturesHorizontalVirtualSlideRouteImport } from './routes/features/horizontal-virtual-slide'
import { Route as FeaturesFastCarouselRouteImport } from './routes/features/fast-carousel'
import { Route as FeaturesDynamicModalRouteImport } from './routes/features/dynamic-modal'
import { Route as FeaturesCubicBezierArrowsRouteImport } from './routes/features/cubic-bezier-arrows'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as ApiTestRouteImport } from './routes/api/test'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesVideoImmersionRoute = FeaturesVideoImmersionRouteImport.update({
  id: '/video-immersion',
  path: '/video-immersion',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesTrelloApiRoute = FeaturesTrelloApiRouteImport.update({
  id: '/trello-api',
  path: '/trello-api',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesHorizontalVirtualSlideRoute =
  FeaturesHorizontalVirtualSlideRouteImport.update({
    id: '/horizontal-virtual-slide',
    path: '/horizontal-virtual-slide',
    getParentRoute: () => FeaturesRoute,
  } as any)
const FeaturesFastCarouselRoute = FeaturesFastCarouselRouteImport.update({
  id: '/fast-carousel',
  path: '/fast-carousel',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesDynamicModalRoute = FeaturesDynamicModalRouteImport.update({
  id: '/dynamic-modal',
  path: '/dynamic-modal',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesCubicBezierArrowsRoute =
  FeaturesCubicBezierArrowsRouteImport.update({
    id: '/cubic-bezier-arrows',
    path: '/cubic-bezier-arrows',
    getParentRoute: () => FeaturesRoute,
  } as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRouteWithChildren
  '/api/test': typeof ApiTestRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/features/cubic-bezier-arrows': typeof FeaturesCubicBezierArrowsRoute
  '/features/dynamic-modal': typeof FeaturesDynamicModalRoute
  '/features/fast-carousel': typeof FeaturesFastCarouselRoute
  '/features/horizontal-virtual-slide': typeof FeaturesHorizontalVirtualSlideRoute
  '/features/trello-api': typeof FeaturesTrelloApiRoute
  '/features/video-immersion': typeof FeaturesVideoImmersionRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/test': typeof ApiTestRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/features/cubic-bezier-arrows': typeof FeaturesCubicBezierArrowsRoute
  '/features/dynamic-modal': typeof FeaturesDynamicModalRoute
  '/features/fast-carousel': typeof FeaturesFastCarouselRoute
  '/features/horizontal-virtual-slide': typeof FeaturesHorizontalVirtualSlideRoute
  '/features/trello-api': typeof FeaturesTrelloApiRoute
  '/features/video-immersion': typeof FeaturesVideoImmersionRoute
  '/features': typeof FeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRouteWithChildren
  '/api/test': typeof ApiTestRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/features/cubic-bezier-arrows': typeof FeaturesCubicBezierArrowsRoute
  '/features/dynamic-modal': typeof FeaturesDynamicModalRoute
  '/features/fast-carousel': typeof FeaturesFastCarouselRoute
  '/features/horizontal-virtual-slide': typeof FeaturesHorizontalVirtualSlideRoute
  '/features/trello-api': typeof FeaturesTrelloApiRoute
  '/features/video-immersion': typeof FeaturesVideoImmersionRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/api/test'
    | '/demo/storybook'
    | '/features/cubic-bezier-arrows'
    | '/features/dynamic-modal'
    | '/features/fast-carousel'
    | '/features/horizontal-virtual-slide'
    | '/features/trello-api'
    | '/features/video-immersion'
    | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/test'
    | '/demo/storybook'
    | '/features/cubic-bezier-arrows'
    | '/features/dynamic-modal'
    | '/features/fast-carousel'
    | '/features/horizontal-virtual-slide'
    | '/features/trello-api'
    | '/features/video-immersion'
    | '/features'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/api/test'
    | '/demo/storybook'
    | '/features/cubic-bezier-arrows'
    | '/features/dynamic-modal'
    | '/features/fast-carousel'
    | '/features/horizontal-virtual-slide'
    | '/features/trello-api'
    | '/features/video-immersion'
    | '/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  ApiTestRoute: typeof ApiTestRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/video-immersion': {
      id: '/features/video-immersion'
      path: '/video-immersion'
      fullPath: '/features/video-immersion'
      preLoaderRoute: typeof FeaturesVideoImmersionRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/trello-api': {
      id: '/features/trello-api'
      path: '/trello-api'
      fullPath: '/features/trello-api'
      preLoaderRoute: typeof FeaturesTrelloApiRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/horizontal-virtual-slide': {
      id: '/features/horizontal-virtual-slide'
      path: '/horizontal-virtual-slide'
      fullPath: '/features/horizontal-virtual-slide'
      preLoaderRoute: typeof FeaturesHorizontalVirtualSlideRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/fast-carousel': {
      id: '/features/fast-carousel'
      path: '/fast-carousel'
      fullPath: '/features/fast-carousel'
      preLoaderRoute: typeof FeaturesFastCarouselRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/dynamic-modal': {
      id: '/features/dynamic-modal'
      path: '/dynamic-modal'
      fullPath: '/features/dynamic-modal'
      preLoaderRoute: typeof FeaturesDynamicModalRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/features/cubic-bezier-arrows': {
      id: '/features/cubic-bezier-arrows'
      path: '/cubic-bezier-arrows'
      fullPath: '/features/cubic-bezier-arrows'
      preLoaderRoute: typeof FeaturesCubicBezierArrowsRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FeaturesRouteChildren {
  FeaturesCubicBezierArrowsRoute: typeof FeaturesCubicBezierArrowsRoute
  FeaturesDynamicModalRoute: typeof FeaturesDynamicModalRoute
  FeaturesFastCarouselRoute: typeof FeaturesFastCarouselRoute
  FeaturesHorizontalVirtualSlideRoute: typeof FeaturesHorizontalVirtualSlideRoute
  FeaturesTrelloApiRoute: typeof FeaturesTrelloApiRoute
  FeaturesVideoImmersionRoute: typeof FeaturesVideoImmersionRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesCubicBezierArrowsRoute: FeaturesCubicBezierArrowsRoute,
  FeaturesDynamicModalRoute: FeaturesDynamicModalRoute,
  FeaturesFastCarouselRoute: FeaturesFastCarouselRoute,
  FeaturesHorizontalVirtualSlideRoute: FeaturesHorizontalVirtualSlideRoute,
  FeaturesTrelloApiRoute: FeaturesTrelloApiRoute,
  FeaturesVideoImmersionRoute: FeaturesVideoImmersionRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  ApiTestRoute: ApiTestRoute,
  DemoStorybookRoute: DemoStorybookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
